// new/frontend/src/lib/components/ui/Button.svelte
<script module>
	import { cva } from 'class-variance-authority';

	export const buttonVariants = cva(
		'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors disabled:pointer-events-none disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 [&_svg]:size-4 [&_svg]:shrink-0',
		{
			variants: {
				variant: {
					primary: 'bg-primary text-primary-foreground hover:bg-primary-hover',
					outline: 'border border-border text-foreground hover:bg-secondary',
					ghost: 'text-muted-foreground hover:bg-secondary hover:text-foreground',
					destructive: 'bg-destructive text-destructive-foreground hover:opacity-90',
					dark: 'bg-foreground text-background hover:opacity-90'
				},
				size: {
					default: 'h-10 px-4',
					sm: 'h-9 px-3 text-[13px]',
					lg: 'h-11 px-6 text-base',
					icon: 'h-9 w-9'
				}
			},
			defaultVariants: { variant: 'primary', size: 'default' }
		}
	);
</script>

<script>
	import { cn } from '$lib/utils';

	// `href` verilibsə <a>, yoxdursa <button> kimi render olunur - köhnə
	// React versiyasındakı `as={Link}` pattern-inin Svelte qarşılığı.
	let { class: className, variant, size, href, children, ...rest } = $props();
</script>

{#if href}
	<a {href} class={cn(buttonVariants({ variant, size }), className)} {...rest}>
		{@render children?.()}
	</a>
{:else}
	<button class={cn(buttonVariants({ variant, size }), className)} {...rest}>
		{@render children?.()}
	</button>
{/if}

// frontend/src/components/ui/button.jsx
import { cva } from 'class-variance-authority';

import { cn } from '@/lib/utils';

export const buttonVariants = cva(
  'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors disabled:pointer-events-none disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 [&_svg]:size-4 [&_svg]:shrink-0',
  {
    variants: {
      variant: {
        primary: 'bg-primary text-primary-foreground hover:bg-primary-hover',
        outline: 'border border-border text-foreground hover:bg-secondary',
        ghost: 'text-muted-foreground hover:bg-secondary hover:text-foreground',
        destructive: 'bg-destructive text-destructive-foreground hover:opacity-90',
        dark: 'bg-foreground text-background hover:opacity-90',
      },
      size: {
        default: 'h-10 px-4',
        sm: 'h-9 px-3 text-[13px]',
        lg: 'h-11 px-6 text-base',
        icon: 'h-9 w-9',
      },
    },
    defaultVariants: { variant: 'primary', size: 'default' },
  },
);

export default function Button({ className, variant, size, as: Comp = 'button', ...props }) {
  return <Comp className={cn(buttonVariants({ variant, size }), className)} {...props} />;
}
