// frontend/src/components/LanguageSwitch.jsx
'use client';

import { Globe } from 'lucide-react';

import { cn } from '@/lib/utils';
import { useLanguage } from '@/context/LanguageContext';

// Tək kliklə dil dəyişdirən düymə - qutu/border olmadan, nav linkləri ilə
// eyni yüngül mətn stilində ki, sağ tərəfdəki düymələr sırasını
// qabartmasın (əvvəllər borderli qutu idi, "3 düymə" kimi ağır görünürdü).
export default function LanguageSwitch({ className }) {
  const { lang, toggle } = useLanguage();

  return (
    <button
      type="button"
      onClick={toggle}
      className={cn(
        'inline-flex items-center gap-1 text-sm font-medium text-muted-foreground transition-colors hover:text-primary',
        className,
      )}
    >
      <Globe className="size-3.5" aria-hidden="true" />
      {lang === 'az' ? 'EN' : 'AZ'}
    </button>
  );
}

// frontend/src/lib/components/LanguageSwitch.svelte
<script>
	import Globe from '@lucide/svelte/icons/globe';
	import { getLocale, setLocale } from '$lib/paraglide/runtime';
	import { cn } from '$lib/utils';

	// Tək kliklə dil dəyişdirən düymə. `setLocale` cookie-ni yeniləyir və
	// səhifəni yenidən yükləyir ki, server-render olunan mətn də (SSR)
	// dərhal düzgün dildə görünsün.
	let { class: className = '' } = $props();
</script>

<button
	type="button"
	onclick={() => setLocale(getLocale() === 'az' ? 'en' : 'az')}
	class={cn(
		'inline-flex items-center gap-1 text-sm font-medium text-muted-foreground transition-colors hover:text-primary',
		className
	)}
>
	<Globe class="size-3.5" aria-hidden="true" />
	{getLocale() === 'az' ? 'EN' : 'AZ'}
</button>
