// frontend/src/components/Navbar.jsx
'use client';

import { useState } from 'react';
import { usePathname } from 'next/navigation';
import { LayoutDashboard, Menu, X } from 'lucide-react';

import BrandLogo from '@/components/BrandLogo';
import LanguageSwitch from '@/components/LanguageSwitch';
import Link from 'next/link';
import Button from '@/components/ui/button';
import { useAuth } from '@/context/AuthContext';
import { useLanguage } from '@/context/LanguageContext';
import { cn } from '@/lib/utils';

const NAV_LINKS = [
  { href: '/', key: 'home' },
  { href: '/donors', key: 'donors' },
  { href: '/requests', key: 'requests' },
];

export default function Navbar() {
  const [menuOpen, setMenuOpen] = useState(false);
  const pathname = usePathname();
  const { t } = useLanguage();
  const { ready, isAuthenticated } = useAuth();

  const isActive = (path) => pathname === path;

  return (
    <nav className="sticky top-0 z-50 border-b border-border bg-background">
      <div className="mx-auto flex h-[68px] max-w-6xl items-center justify-between px-6 lg:grid lg:grid-cols-3">
        <BrandLogo className="lg:justify-self-start" />

        <ul className="hidden items-center gap-9 lg:flex lg:justify-self-center">
          {NAV_LINKS.map((link) => (
            <li key={link.key}>
              <Link
                href={link.href}
                className={cn(
                  'text-sm font-medium text-muted-foreground transition-colors hover:text-primary',
                  isActive(link.href) && 'text-primary',
                )}
              >
                {t.nav[link.key]}
              </Link>
            </li>
          ))}
        </ul>

        <div className="hidden items-center gap-5 lg:flex lg:justify-self-end">
          <LanguageSwitch />
          {ready && (isAuthenticated ? (
            <Button as={Link} href="/dashboard" size="sm">
              <LayoutDashboard aria-hidden="true" /> {t.nav.dashboard}
            </Button>
          ) : (
            <>
              <Link href="/signin" className="text-sm font-medium text-muted-foreground transition-colors hover:text-primary">
                {t.nav.login}
              </Link>
              <Button as={Link} href="/signup" size="sm">{t.nav.register}</Button>
            </>
          ))}
        </div>

        <button
          type="button"
          className="flex size-9 items-center justify-center rounded-lg text-foreground transition-colors hover:bg-secondary lg:hidden"
          onClick={() => setMenuOpen((open) => !open)}
          aria-label="Toggle menu"
        >
          {menuOpen ? <X aria-hidden="true" /> : <Menu aria-hidden="true" />}
        </button>
      </div>

      {menuOpen && (
        <div className="absolute inset-x-0 top-full z-40 flex max-h-[calc(100vh-68px)] flex-col gap-4 overflow-y-auto border-t border-border bg-background px-6 py-5 shadow-lg lg:hidden">
          {NAV_LINKS.map((link) => (
            <Link key={link.key} href={link.href} onClick={() => setMenuOpen(false)} className="text-base font-medium text-foreground">
              {t.nav[link.key]}
            </Link>
          ))}
          <LanguageSwitch className="w-fit text-base" />
          {ready && (isAuthenticated ? (
            <Button as={Link} href="/dashboard" size="sm" className="w-fit" onClick={() => setMenuOpen(false)}>
              <LayoutDashboard aria-hidden="true" /> {t.nav.dashboard}
            </Button>
          ) : (
            <div className="flex items-center gap-4">
              <Link href="/signin" onClick={() => setMenuOpen(false)} className="text-base font-medium text-foreground">
                {t.nav.login}
              </Link>
              <Button as={Link} href="/signup" size="sm" onClick={() => setMenuOpen(false)}>{t.nav.register}</Button>
            </div>
          ))}
        </div>
      )}
    </nav>
  );
}

// frontend/src/lib/components/Navbar.svelte
<script>
	import LayoutDashboard from '@lucide/svelte/icons/layout-dashboard';
	import Menu from '@lucide/svelte/icons/menu';
	import X from '@lucide/svelte/icons/x';
	import { page } from '$app/state';
	import * as m from '$lib/paraglide/messages.js';
	import BrandLogo from '$lib/components/BrandLogo.svelte';
	import LanguageSwitch from '$lib/components/LanguageSwitch.svelte';
	import ThemeToggle from '$lib/components/ThemeToggle.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import { cn } from '$lib/utils';

	const NAV_LINKS = [
		{ href: '/', key: 'home', label: m.nav_home },
		{ href: '/donors', key: 'donors', label: m.nav_donors },
		{ href: '/requests', key: 'requests', label: m.nav_requests },
		{ href: '/about', key: 'about', label: m.nav_about },
	];

	let menuOpen = $state(false);
	let isAuthenticated = $derived(Boolean(page.data.user));
	let isActive = (path) => page.url.pathname === path;
</script>

<nav class="sticky top-0 z-50 border-b border-border bg-background">
	<div class="mx-auto flex h-[68px] max-w-6xl items-center justify-between px-6 lg:grid lg:grid-cols-3">
		<BrandLogo class="lg:justify-self-start" />

		<ul class="hidden items-center gap-7 lg:flex lg:justify-self-center">
			{#each NAV_LINKS as link (link.key)}
				<li>
					<a
						href={link.href}
						class={cn(
							'text-sm font-medium text-muted-foreground transition-colors hover:text-primary',
							isActive(link.href) && 'text-primary'
						)}
					>
						{link.label()}
					</a>
				</li>
			{/each}
		</ul>

		<div class="hidden items-center gap-3 lg:flex lg:justify-self-end">
			<div class="flex items-center gap-1">
				<ThemeToggle />
				<LanguageSwitch />
			</div>
			{#if isAuthenticated}
				<Button href="/dashboard" size="sm">
					<LayoutDashboard aria-hidden="true" />
					{m.nav_dashboard()}
				</Button>
			{:else}
				<div class="flex items-center gap-2">
					<Button href="/signin" variant="outline" size="sm">{m.nav_login()}</Button>
					<Button href="/signup" size="sm">{m.nav_register()}</Button>
				</div>
			{/if}
		</div>

		<button
			type="button"
			class="flex size-9 items-center justify-center rounded-lg text-foreground transition-colors hover:text-primary lg:hidden"
			onclick={() => (menuOpen = !menuOpen)}
			aria-label="Toggle menu"
		>
			{#if menuOpen}
				<X aria-hidden="true" />
			{:else}
				<Menu aria-hidden="true" />
			{/if}
		</button>
	</div>

	{#if menuOpen}
		<div class="absolute inset-x-0 top-full z-40 flex max-h-[calc(100vh-68px)] flex-col gap-4 overflow-y-auto border-t border-border bg-background px-6 py-5 shadow-lg lg:hidden">
			{#each NAV_LINKS as link (link.key)}
				<a href={link.href} onclick={() => (menuOpen = false)} class="text-base font-medium text-foreground">
					{link.label()}
				</a>
			{/each}
			<div class="flex items-center justify-between">
				{#if isAuthenticated}
					<Button href="/dashboard" size="sm" class="w-fit" onclick={() => (menuOpen = false)}>
						<LayoutDashboard aria-hidden="true" />
						{m.nav_dashboard()}
					</Button>
				{:else}
					<div class="flex items-center gap-2">
						<Button href="/signin" variant="outline" size="sm" onclick={() => (menuOpen = false)}>{m.nav_login()}</Button>
						<Button href="/signup" size="sm" onclick={() => (menuOpen = false)}>{m.nav_register()}</Button>
					</div>
				{/if}
				<div class="flex items-center gap-2">
					<ThemeToggle />
					<LanguageSwitch class="w-fit text-base" />
				</div>
			</div>
		</div>
	{/if}
</nav>
